--- # Configuration for the Fantasy LCS stats script

# Database credentials
database:
    username:   'username'
    password:   'password'

# Date of the earliest incomplete fetch
next-fetch: '2010-01-01'

